"""Add amount column to Authorization and Purchase models

Revision ID: 1cdbc987cc55
Revises: ddfc78dd2985
Create Date: 2024-05-28 00:22:29.232528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdbc987cc55'
down_revision = 'ddfc78dd2985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('doc_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('User', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_fees', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('service_fees')

    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.drop_constraint('Doc', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('doc_url')
        batch_op.drop_column('title')

    op.create_table('client_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('qr_code_url', sa.VARCHAR(), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
