"""typo mismatch in Authorizatin fixed

Revision ID: 40e2ca8812fa
Revises: a576042da18b
Create Date: 2024-05-25 22:40:33.911231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e2ca8812fa'
down_revision = 'a576042da18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_last_name', sa.String(), nullable=False))
        batch_op.create_unique_constraint('Unique', ['client_last_name'])

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('author_address',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('author_address',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('client_last_name')

    # ### end Alembic commands ###
