"""Authorization model final adjustments

Revision ID: 482ce7b827f4
Revises: 7ccd151fb9a2
Create Date: 2024-05-25 22:47:53.538980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482ce7b827f4'
down_revision = '7ccd151fb9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.alter_column('provider_email1',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('provider_name1',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.alter_column('provider_name1',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('provider_email1',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
