"""Folders to Purchase class rename

Revision ID: 621aa5048e36
Revises: e6d5c9802af7
Create Date: 2024-05-24 14:22:04.855481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621aa5048e36'
down_revision = 'e6d5c9802af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('owner_first_name', sa.VARCHAR(), nullable=False),
    sa.Column('owner_last_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('doc_url', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('start_check', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
