"""client location column added authorization

Revision ID: 7ccd151fb9a2
Revises: 40e2ca8812fa
Create Date: 2024-05-25 22:44:15.802730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccd151fb9a2'
down_revision = '40e2ca8812fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_location', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.drop_column('client_location')

    # ### end Alembic commands ###
