"""one column removed in Invoice model

Revision ID: 88431fbbd707
Revises: baef3733b62f
Create Date: 2024-05-21 09:57:42.720711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88431fbbd707'
down_revision = 'baef3733b62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
