"""Purchase model columns added

Revision ID: 917067e90ff3
Revises: 621aa5048e36
Create Date: 2024-05-24 14:53:07.283400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917067e90ff3'
down_revision = '621aa5048e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('author_first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('author_last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('author_email_address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('product_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('product_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('author_phone_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('product_picture_url', sa.String(), nullable=True))
        batch_op.drop_column('owner_last_name')
        batch_op.drop_column('owner_first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_first_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('owner_last_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('product_picture_url')
        batch_op.drop_column('provider')
        batch_op.drop_column('location')
        batch_op.drop_column('author_phone_number')
        batch_op.drop_column('product_width')
        batch_op.drop_column('product_length')
        batch_op.drop_column('author_email_address')
        batch_op.drop_column('author_last_name')
        batch_op.drop_column('author_first_name')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
