"""new model added for store

Revision ID: 93f3673879d4
Revises: e0cca4f28582
Create Date: 2024-06-12 19:58:35.948109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f3673879d4'
down_revision = 'e0cca4f28582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_file_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('logo_file_url')

    # ### end Alembic commands ###
