"""new columns added in product model

Revision ID: b9951d2ca617
Revises: b22e8d717d8e
Create Date: 2024-06-15 18:13:19.942852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9951d2ca617'
down_revision = 'b22e8d717d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('provider', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('provider_location', sa.String(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('provider_location')
        batch_op.drop_column('provider')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
