"""job models updated

Revision ID: c10000aaf6c1
Revises: 4f597c8bcdca
Create Date: 2024-05-20 10:09:14.075935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10000aaf6c1'
down_revision = '4f597c8bcdca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('salary', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('posted_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('closing_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('annual_wage')
        batch_op.drop_column('end_at')
        batch_op.drop_column('start_from')
        batch_op.drop_column('monthly_wage')
        batch_op.drop_column('require_travel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_travel', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('monthly_wage', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('start_from', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('end_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('annual_wage', sa.FLOAT(), nullable=False))
        batch_op.drop_column('closing_date')
        batch_op.drop_column('posted_date')
        batch_op.drop_column('salary')
        batch_op.drop_column('location')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
