"""job models updated

Revision ID: c798a99c52cb
Revises: c10000aaf6c1
Create Date: 2024-05-20 10:11:50.104320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c798a99c52cb'
down_revision = 'c10000aaf6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
