"""messages model added

Revision ID: d6f5d2a4e72b
Revises: 3ce3d07c2a00
Create Date: 2024-06-11 20:59:23.576817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f5d2a4e72b'
down_revision = '3ce3d07c2a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key('sender_id', 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key('receiver_id', 'users', ['receiver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_column('file_url')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
