"""job & job_applications model redifinitions

Revision ID: e6d5c9802af7
Revises: fe8defcd3fe6
Create Date: 2024-05-24 01:41:21.374979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d5c9802af7'
down_revision = 'fe8defcd3fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('employee_first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('employee_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('employee_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('employee_first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
