"""service fees column added in Authorization

Revision ID: fc98b4c16832
Revises: 482ce7b827f4
Create Date: 2024-05-26 10:44:48.693457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc98b4c16832'
down_revision = '482ce7b827f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_fees', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorizations', schema=None) as batch_op:
        batch_op.drop_column('service_fees')

    # ### end Alembic commands ###
